name: Catalog Service

on:
  push:
    paths:
      - catalog-service/**
    branches:
      - "**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      working-directory: ./catalog-service
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Give Maven wrapper execute permission
        run: chmod +x mvnw

      - name: Run Maven verify
        run: ./mvnw -ntp verify
